name: CI - SAST & Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sast_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit

      - name: Run Bandit (fail on HIGH/HIGH)
        run: |
          bandit -r . -lll -iii -x venv,tests,migrations -f json -o bandit-report.json

      - name: Upload Bandit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

      - name: Build artifact (zip source)
        if: success()
        run: |
          mkdir -p dist
          git ls-files | zip -@ dist/source.zip

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: source-zip
          path: dist/source.zip
